### ISSUE TITLE
Not issue but possible new feature.

### ISSUE THREAD

**Issue by Rand-o** [rickyzhang82/tethering#17]
Hi Ricky,

So a previous jailbreak tweak had worked similar to your app but allowed full tethering. Not just browser connectivity. The way they did this was they ported tun2socks to iOS to use with their app.

"tun2socks is used to "socksify" TCP (IPv4 and IPv6) connections at the network layer. It implements a TUN virtual network interface which accepts all incoming TCP connections (regardless of destination IP), and forwards them through a SOCKS server. This allows you to forward all connections through SOCKS, without any need for application support."

I am a Network engineer but I don't do any programming, otherwise I would try to make this work. This would be a great addition to this app to allow FULL tethering.

Code for tun2socks can be found here https://code.google.com/p/badvpn/wiki/tun2socks

**Comment by rickyzhang82** [comment]
I'm against iOS jailbreak. Because they does not open all their source code. As you know smartphone these day stores more personal data than your PC, I can't trust anybody mess around it without knowing their incentive why they spend time and resource to find the vulnerability of iOS and create a backdoor. Of course, the same argument can apply to iOS, which Apple doesn't open their source code. It may have unknown backdoor. But if it does, those smart jailbreakers should have found it already.

In any case, I don't plan to support any features that requires jailbreak. In fact, if you really want this: you can mess around your PC/Mac to create a fake router and then forward sockify connection to iPhone.

**Comment by Rand-o** [comment]
Sorry f it was unclear, this does not require a jailbreak at all but would give similar functionality to an existing tweak that allows full tethering

**Comment by greatquux** [comment]
I think you want the app to set up a virtual network interface on the phone, one that would accept all the connections over this interface and send them out through the SOCKS server (which would probably not even be necessary at that point).  I'm not sure he'd be able to implement his own network interface in iOS without jailbreaking - Apple has a lot of restrictions and a normal app might not be able to do that.  As it is, there is no way this app would ever be accepted by the App Store.  

You can use tun2socks or proxychains-ng on a computer (not sure if they work on Windows) there are commercial products like Proxifier or ProxyCap also.   I've done some experimenting with proxychains-ng for the Mac and gotten it to work for my use cases when I am travelling, though I need to do some more experimentation on Windows. that I haven't gotten around to yet.

Apple's restrictions make it harder to do this on OS X - the Wiki here documents some problems with DNS resolution on Mavericks and above which is weird (but Firefox gets around it as long as you have the "Remote DNS" box checked in the Proxy config).   And because of System Integrity Protection on 10.11, you can't socksify system binaries that are run out of system directories.  For example, if you try to use proxychains-ng on the ssh binary in /usr/bin/ssh, it doesn't work.  But if I copy /usr/bin/ssh to /tmp/ssh and then run it through proxychains-ng, it does work. 

Coming from the Android world it was hard to give up being able to root my device and do whatever I wanted.  But I'm happy at least this project lets me get basic web browsing and remote desktop and ssh through my phone.

**Comment by rickyzhang82** [comment]
To create a tun/tap in iOS requires jailbreak. It is easier to do it in you PC/Mac.
