### ISSUE TITLE
Stream Open Error

### ISSUE THREAD

**Issue by diaruys** [rickyzhang82/tethering#40]
Since I updated my iPhone SE to iOS 12.3, every time I tethered with my laptop running on Windows 10, there’s a problem with the connection. The status will show “stream open error” very frequently which will interrupt any ongoing download and page load. Sometimes it just went “recieved” and I have to restart the app in order to continue using it.

I’ve look for a solution on the internet and still haven’t found one yet.

**Comment by rickyzhang82** [comment]
You can enable debug mode and see what went wrong by yourself.

**Comment by diaruys** [comment]
How can I do that? Can you please explain more? I’m sorry I’m still new into this.

**Comment by diaruys** [comment]
How do I do it? I’m sorry I’m still new into this.

**Comment by rickyzhang82** [comment]
https://github.com/rickyzhang82/tethering/wiki/Debugging

**Comment by rickyzhang82** [comment]
Do you get the binary from somewhere?

**Comment by Bronus** [comment]
I have a little more stable now, I downloaded an ipa tethering app. I just created a static ip in the iphone wifi settings. I also created a mac VM and have been troubleshooting it

**Comment by rickyzhang82** [comment]
I don’t recommend anyone get an unknown source IPA and install to your iPhone. Honestly, you put yourself at risk. Whoever provide you this, he can do whatever evil things they want. 

So good luck.

**Comment by rickyzhang82** [comment]
@diaruys 

If you also get an IPA from somewhere like @Bronus, I myself won’t support other’s binary release. Ask whoever give you IPA for help.

God knows what they add and what kind of motivation to release the IPA binary.

The code has been extremely stable since iOS 7 in 2013. If I were you, I would uninstall it IMMEDIATELY and compile my repo from the source code. You can **NOT** workaround such huge security problems even you connect to a VPN from your iPhone. They could redirect your request to their man in the middle server and steal your credentials.

Man, you guys are adults. Why makes such mistakes?
