### ISSUE TITLE
unsupported socks protocol when connect with windows 10

### ISSUE THREAD

**Issue by sooxiaotong** [rickyzhang82/tethering#47]
@rickyzhang82   I'm using my phone as hotspot, both of my Mac and PC connect to it, Mac works well with default socks proxy settings, but it won't work on windows. It shows the error below. I tried using proxifier, pac, and socks all showing the same error... 

![image](https://user-images.githubusercontent.com/13378059/68531914-9168fd80-0352-11ea-8fc5-54e576388b69.png)

_Originally posted by @sooxiaotong in https://github.com/rickyzhang82/tethering/issues/46#issuecomment-552116312_

**Comment by rickyzhang82** [comment]
The tethering app only supports socks 5.  I don't have Windows 10 laptop to test it.

According to [reddit post](https://www.reddit.com/r/techsupport/comments/4j0l35/windows_10_route_all_traffic_through_socks5_proxy/), you need to explicitly use `socks5 `, instead of  `socks`.

In my pac file implementation, you can use `http://your-iphone-name:8080/socks5.pac` to specify socks5 protocol.

If the pac file solution doesn't work, follow the reddit post above and manually setup `socks5://your-iphone-ip`

**Comment by sooxiaotong** [comment]
I tried all of these settings, only http://my-iphone-ip:8080/socks5.pac works! and please change your document the pac name should be socks5.pac instead of socks.pac, because only socks5.pac will work on windows 10
