### ISSUE TITLE
request for UDP support

### ISSUE THREAD

**Issue by sooxiaotong** [rickyzhang82/tethering#49]
Stop closing my issue, and I'm not abusing. Here's some example for implementing UDP forwarding.

https://github.com/yichengchen/Potatso-iOS/blob/master/Library/ShadowPath/ShadowPath/Antinat/server/socks5.m
https://github.com/mordasov/AsyncProxy
https://blog.csdn.net/whatday/article/details/40183555

**Comment by rickyzhang82** [comment]
According to [RFC 1928](https://tools.ietf.org/html/rfc1928), I apologize that socks5 dose support UDP.

Feel free to send me a PR.

**Comment by rickyzhang82** [comment]
socks5 can't forward ICMP. You definitely need some reading in OSI model. That's why I close your previous issue.

I know there are a lot of code out there in Internet. But you need to read it, understand it, verify it with RFC and test it. This requires a lot of time and effort. 

After skimming through [RFC 1928](https://tools.ietf.org/html/rfc1928), I personally won't add support for UDP association in socks5 proxy here. I don't have any use case that requires forwarding UDP. I already added DNS server in tethering app. I honestly don't have anything missing in terms of UDP forwarding.

I will close the issue. 

I'm happy to merge your PR. I'd suggest you start to read [socks proxy implementation here](https://github.com/rickyzhang82/tethering/blob/master/SocksProxy.mm) and see how to add UDP forward support according to the RFC.

**Comment by tmaly1980** [comment]
@rickyzhang82 Are you suggesting that UDP support is not available? Would this explain why my OpenVPN client does not work through the proxy? Any suggestions how one might implement UDP support? ie where the code might belong in the SocskProxy.mm file?

**Comment by rickyzhang82** [comment]
No UDP support in proxy.  Run OpenVPN in your iOS, instead.

**Comment by thpryrchn** [comment]
> 

How do you do that? I am going to another country next month, and my carries doesn't let tethering work in another country with my plan.
