### ISSUE TITLE
Stops when receiving phone calls

### ISSUE THREAD

**Issue by tmaly1980** [rickyzhang82/tethering#51]
For some reason the app seems to disconnect/stop whenever I receive a phone call. If I end up on the phone with someone, I have to go to the app and press Start for my computer to be back online. Is this something we have control over, ie modifications to the code? Or is it a device issue? 

Is there a way to have it attempt to reconnect a few times (ie 3-4) when it accidentally stops - so I don't need to mess with it? There are also other times it seems where it will stop out of nowhere.

**Comment by rickyzhang82** [comment]
In AT&T's commercial, I knew that iPhone in CDMA operator's network like Verizon can **not** do voice call and data transmission at the same time. I'm not sure this applies to your case.

Regarding to your suggestion of re-connection, the App is a DNS forward server + Socks proxy server. It's client's job to post the request again when the data service is not available.

I have never experienced the app crashed for years. The stop of data transmission may be caused by other reason.

Some user suggest that uses VPN in iOS to evade mobile operator's network detection on computer network traffic. It is easy to tell that if the web request (http/https) is from desktop or mobile nowadays. Use encryption may mitigate the stop.

**Comment by tmaly1980** [comment]
I'm not saying the app crashes. It just stops forwarding. Has nothing to do with my carrier detecting the proxy. The red "STOP" button turns to the green "START" button. Happens when I receive a phone call, text message, and possibly a few other phone interruptions. It would just be nice if there was a mechanism to retry connecting (a few times) if it loses connection unexpectedly. Something that could be configured (ie # of tries) would be ideal (ie disabled by default).

**Comment by rickyzhang82** [comment]
I don't stop the proxy by the interruption you mentioned. The app runs in background mode by looping a silent music. Even you turn off the screen, the app still runs.

Do you compile the app from source code or get it from somebody's pre-compiled binary?

**Comment by tmaly1980** [comment]
Well a phone call being received is going to stop the playback of any audio/video. So would that kill the connection of the silent audio is interrupted/paused?

**Comment by tmaly1980** [comment]
@rickyzhang82 This problem can be repeated simply by making a phone call while the proxy is running. When you return back to the app it will turn off (shows the green START button). I have to manually re-start it. It also happens when anyone calls my phone. Is that making sense?

Can you advice on how to fix this?

**Comment by rickyzhang82** [comment]
I heard what you said. To implement what you want -- automatically restart proxy after the phone call interrupts the app, you need the following:

- The app need write a call back when it interrupts by phone call.
- The call back function saves the previous state somewhere (started or stopped).
- The app resumes the previous state when interruption ends.

The app is already a background one with audio playback. The phone call may interrupt audio playback. I doubt you can write a universal solution that keep proxy running during phone call. Because CDMA can make voice call and data transfer at the same time. Your research may focus on resume the state when phone call interrupts.

Please feel free to send me a PR.
