### ISSUE TITLE
Both case1 and case2 failed. AT&T. IOS 14

### ISSUE THREAD

**Issue by minweny** [rickyzhang82/tethering#54]
First of all, I want to say this app is a genius app. Still thinking where I got the configuration wrong.

![690e0fdc93e2bafb6895a3cac107444](https://user-images.githubusercontent.com/25225921/103249224-d32c7d00-4933-11eb-9b02-1c67aae49916.jpg)

Your instructions (https://github.com/rickyzhang82/tethering/wiki/Configuration) and Rand_o's (https://www.reddit.com/r/iphone/comments/41cx00/sideload_a_tethering_app_for_your_iphone/) are very detailed. I followed them carefully.

Have tried case1 and case2. Tesing environment includes Macbook pro, Windows10, Chromebook.

**Comment by basicaneer** [comment]
Having the same issue on iOS 14.1 with my iPhone 12 and Windows 10 PC. I configured it using the Reddit posts & configuration instructions here and a few other methods but it's not letting any data get through.

**Comment by mysk10** [comment]
Same issue; same software/hardware

**Comment by mrfanch** [comment]
Issue persists on iOS 14.3 (and appears to exist since at least iOS 14.1). Configuration on Mac via Firefox w/Socks 5 proxy settings. The app will not let data pass through.

**Comment by MrVas** [comment]
This is a complete shot in the dark, and it has been a while since I built and used the Tethering app, but iOS 14 introduced a "Local Network" feature that appears to be enabled for data to flow properly between the interfaces. I believe that Tethering should be listed under Settings -> Privacy -> Local Network, and the option enabled for Tethering to work.

Quote and example below.

"Apple iOS 14 and above include a new app setting called "Local Network", which when enabled allows the app to identify devices you connect to via Wi-Fi. ForeFlight needs this setting to be enabled so it can communicate with Wi-Fi connected devices..."

https://support.foreflight.com/hc/en-us/articles/360057545233-Why-is-my-Stratus-not-showing-up-on-the-Device-page-

Hope this helps!
     On Monday, January 18, 2021, 01:05:39 AM PST, mrfanch <notifications@github.com> wrote:  
 
 


Issue persists on iOS 14.3 (and appears to exist since at least iOS 14.1). Configuration on Mac via Firefox w/Socks 5 proxy settings. The app will not let data pass through.

**Comment by linzycumbia** [comment]
I was having issues with code becoming unresponsive. I forked the project and made some changes that got everything working again on iOS 14.0-14.3

https://github.com/linzycumbia/Tethering2

Maybe it will work for you too.

**Comment by rickyzhang82** [comment]
@MrVas 

Thanks for pointing it out. I added local network requests and declared Bonjour services in info.plist.

I tested it in iOS14. It works again.

Please give a try on V1.8 release.
